
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsnjomohexvuwfasverp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzbmpvbW9oZXh2dXdmYXN2ZXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjMxMTIsImV4cCI6MjA2MTA5OTExMn0.jCJq4iB_iw0r2KmO81UtKkByEWBvCiPiDf_95v2PTWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: (() => { try { return window.localStorage } catch { return undefined as any } })(),
    autoRefreshToken: true,
    persistSession: true,
  }
});
